# Generated by Django 5.0.2 on 2024-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monsters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsName', models.CharField(max_length=200)),
                ('monsScientificName', models.CharField(max_length=200)),
                ('monsType', models.CharField(max_length=200)),
                ('monsHigh', models.CharField(max_length=200)),
                ('monsLength', models.CharField(max_length=200)),
                ('monsWeight', models.CharField(max_length=200)),
                ('monsDiet', models.CharField(max_length=200)),
                ('monsBiome', models.CharField(max_length=200)),
                ('monsSocialBehaviour', models.CharField(max_length=200)),
            ],
        ),
    ]
