# Generated by Django 5.0.2 on 2024-02-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonstersDataBase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsters',
            name='monsWeight',
        ),
    ]
