# Generated by Django 5.0.2 on 2024-03-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonstersDataBase', '0003_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
