# Generated by Django 5.0.2 on 2024-03-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonstersDataBase', '0004_delete_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
