# Generated by Django 5.0.2 on 2024-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonstersDataBase', '0006_feedbackform_delete_user_alter_monsters_monstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsters',
            name='monsType',
            field=models.CharField(choices=[('1', 'Mammal'), ('2', 'Bird'), ('3', 'Reptilia'), ('4', 'Fish')], max_length=20),
        ),
    ]
