# Generated by Django 5.0.2 on 2024-04-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonstersDataBase', '0009_alter_monsters_monstype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monsters',
            old_name='monsType',
            new_name='Type',
        ),
    ]
